version: "3"
services:
  blog-service:
    build: .
    image: blog-springboot:latest
    container_name: blog-springboot
    restart: always
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - "/usr/local/upload:/usr/local/upload"
    ports:
      - "8080:8080"
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    restart: always
    command: --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms64m -Xmx128m"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "${ELASTICSEARCH_PASSWORD}"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net
  kibana:
    image: kibana:${ELASTICSEARCH_VERSION}
    container_name: kibana
    volumes:
      - "/usr/local/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - es-net
  canal_server:
    image: canal/canal-server:${CANAL_VERSION}
    container_name: canal
    volumes:
      - "/usr/local/canal/instance.properties:/home/admin/canal-server/conf/example/instance.properties"
      - "/usr/local/canal/canal.properties:/home/admin/canal-server/conf/canal.properties"
    ports:
      - "11111:11111"
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    restart: always
    volumes:
      - "/usr/local/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "/usr/local/vue:/usr/local/vue"
      - "/usr/local/upload:/usr/local/upload"
    privileged: true
    ports:
      - "443:443"
      - "80:80"
networks:
  es-net:
    driver: bridge